import { useEffect, useState } from 'react';
import CompanyList from '../components/CompanyList';
import { getCompanies } from '../components/api';

function CompaniesPage() {
  const [companies, setCompanies] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let isMounted = true;

    async function loadCompanies() {
      try {
        const data = await getCompanies();
        if (!isMounted) return;
        setCompanies(data);
      } catch (err) {
        if (!isMounted) return;
        setError(err.message || 'Failed to load companies.');
      } finally {
        if (isMounted) setLoading(false);
      }
    }

    loadCompanies();
    return () => {
      isMounted = false;
    };
  }, []);

  if (loading) return <p className="muted">Loading companies...</p>;
  if (error) return <p className="error">{error}</p>;

  return (
    <section className="stack-md">
      <div className="card">
        <h1>Companies</h1>
        <p className="muted">Structured profiles generated by the ingestion pipeline.</p>
      </div>
      <CompanyList companies={companies} />
    </section>
  );
}

export default CompaniesPage;
